/* ============================================
   VOY — Mock Data
   Quinta Región, Chile
   ============================================ */

const VOY_DATA = {

  categories: [
    { id: 'gasfiteria',  label: 'Gasfitería',    icon: 'fa-faucet',          color: '#2563EB', bg: '#DBEAFE' },
    { id: 'electricidad',label: 'Electricidad',  icon: 'fa-bolt',            color: '#0EA5E9', bg: '#E0F2FE' },
    { id: 'pintura',     label: 'Pintura',       icon: 'fa-paint-roller',    color: '#8B5CF6', bg: '#EDE9FE' },
    { id: 'mecanica',    label: 'Mecánica',      icon: 'fa-wrench',          color: '#F59E0B', bg: '#FEF3C7' },
    { id: 'belleza',     label: 'Belleza',       icon: 'fa-scissors',        color: '#EC4899', bg: '#FCE7F3' },
    { id: 'profesores',  label: 'Clases',        icon: 'fa-book-open',       color: '#10B981', bg: '#D1FAE5' },
    { id: 'baile',       label: 'Baile',         icon: 'fa-music',           color: '#F97316', bg: '#FFEDD5' },
    { id: 'limpieza',    label: 'Limpieza',      icon: 'fa-broom',           color: '#14B8A6', bg: '#CCFBF1' },
  ],

  workers: [
    {
      id: 1,
      name: 'Carlos Muñoz',
      avatar: 'https://i.pravatar.cc/128?img=11',
      category: 'gasfiteria',
      categoryLabel: 'Gasfitería',
      rating: 4.9,
      reviews: 187,
      distance: 1.2,
      priceMin: 20000,
      priceMax: 60000,
      priceUnit: 'visita',
      city: 'Viña del Mar',
      lat: -33.024,
      lng: -71.552,
      verified: true,
      available: true,
      completedJobs: 312,
      responseTime: '~15 min',
      bio: 'Gasfiter certificado con 9 años de experiencia. Especializado en instalaciones, filtraciones y emergencias 24/7. Trabajo limpio y garantizado.',
      skills: ['Filtraciones', 'Calefont', 'Instalaciones', 'Desagüe', 'Emergencias'],
      gallery: [
        'https://picsum.photos/seed/gasfit1/300/200',
        'https://picsum.photos/seed/gasfit2/300/200',
        'https://picsum.photos/seed/gasfit3/300/200',
      ],
    },
    {
      id: 2,
      name: 'Roberto Soto',
      avatar: 'https://i.pravatar.cc/128?img=15',
      category: 'electricidad',
      categoryLabel: 'Electricidad',
      rating: 4.8,
      reviews: 143,
      distance: 2.4,
      priceMin: 25000,
      priceMax: 80000,
      priceUnit: 'proyecto',
      city: 'Viña del Mar',
      lat: -33.031,
      lng: -71.540,
      verified: true,
      available: true,
      completedJobs: 256,
      responseTime: '~20 min',
      bio: 'Electricista SEC clase A con 12 años de trayectoria. Instalaciones residenciales y comerciales, tableros, iluminación LED.',
      skills: ['Tableros', 'Iluminación LED', 'Instalaciones', 'Certificación SEC', 'Domótica'],
      gallery: [
        'https://picsum.photos/seed/elec1/300/200',
        'https://picsum.photos/seed/elec2/300/200',
      ],
    },
    {
      id: 3,
      name: 'Ana Ramírez',
      avatar: 'https://i.pravatar.cc/128?img=5',
      category: 'belleza',
      categoryLabel: 'Belleza',
      rating: 5.0,
      reviews: 98,
      distance: 0.8,
      priceMin: 15000,
      priceMax: 50000,
      priceUnit: 'sesión',
      city: 'Valparaíso',
      lat: -33.045,
      lng: -71.620,
      verified: true,
      available: true,
      completedJobs: 189,
      responseTime: '~10 min',
      bio: 'Estilista y maquilladora profesional. Cortes, colorimetría, peinados para eventos y maquillaje artístico. Trabajo a domicilio.',
      skills: ['Corte', 'Colorimetría', 'Peinado', 'Maquillaje', 'Uñas'],
      gallery: [
        'https://picsum.photos/seed/beauty1/300/200',
        'https://picsum.photos/seed/beauty2/300/200',
      ],
    },
    {
      id: 4,
      name: 'Diego Herrera',
      avatar: 'https://i.pravatar.cc/128?img=20',
      category: 'pintura',
      categoryLabel: 'Pintura',
      rating: 4.7,
      reviews: 61,
      distance: 3.1,
      priceMin: 30000,
      priceMax: 150000,
      priceUnit: 'proyecto',
      city: 'Quilpué',
      lat: -33.048,
      lng: -71.443,
      verified: true,
      available: false,
      completedJobs: 94,
      responseTime: '~30 min',
      bio: 'Pintor de interiores y exteriores con 7 años de experiencia. Trabajo prolijo, materiales de primera. Presupuesto sin costo.',
      skills: ['Interiores', 'Exteriores', 'Estuco', 'Barniz', 'Pintura decorativa'],
      gallery: [
        'https://picsum.photos/seed/pintor1/300/200',
        'https://picsum.photos/seed/pintor2/300/200',
      ],
    },
    {
      id: 5,
      name: 'Javier Contreras',
      avatar: 'https://i.pravatar.cc/128?img=33',
      category: 'mecanica',
      categoryLabel: 'Mecánica',
      rating: 4.8,
      reviews: 212,
      distance: 4.5,
      priceMin: 20000,
      priceMax: 200000,
      priceUnit: 'servicio',
      city: 'Concón',
      lat: -32.920,
      lng: -71.530,
      verified: true,
      available: true,
      completedJobs: 405,
      responseTime: '~25 min',
      bio: 'Mecánico automotriz especializado en vehículos japoneses y coreanos. Diagnóstico computarizado, frenos, suspensión y motor.',
      skills: ['Diagnóstico', 'Frenos', 'Suspensión', 'Motor', 'Cambio de aceite'],
      gallery: [
        'https://picsum.photos/seed/mec1/300/200',
        'https://picsum.photos/seed/mec2/300/200',
      ],
    },
    {
      id: 6,
      name: 'Valentina Lagos',
      avatar: 'https://i.pravatar.cc/128?img=9',
      category: 'profesores',
      categoryLabel: 'Clases',
      rating: 4.9,
      reviews: 77,
      distance: 1.8,
      priceMin: 15000,
      priceMax: 30000,
      priceUnit: 'hora',
      city: 'Viña del Mar',
      lat: -33.020,
      lng: -71.560,
      verified: true,
      available: true,
      completedJobs: 143,
      responseTime: '~15 min',
      bio: 'Profesora de matemáticas y física para enseñanza media y pre-universitaria. Egresada de Ingeniería Civil PUCV. Clases online y presenciales.',
      skills: ['Matemáticas', 'Física', 'PSU/PTU', 'Pre-universitario', 'Álgebra'],
      gallery: [],
    },
    {
      id: 7,
      name: 'Camila Rojas',
      avatar: 'https://i.pravatar.cc/128?img=47',
      category: 'baile',
      categoryLabel: 'Baile',
      rating: 5.0,
      reviews: 54,
      distance: 2.2,
      priceMin: 20000,
      priceMax: 35000,
      priceUnit: 'hora',
      city: 'Viña del Mar',
      lat: -33.035,
      lng: -71.555,
      verified: true,
      available: true,
      completedJobs: 89,
      responseTime: '~10 min',
      bio: 'Bailarina y profesora certificada de salsa, bachata y kizomba. 8 años de experiencia. Clases individuales, en pareja y grupos pequeños.',
      skills: ['Salsa', 'Bachata', 'Kizomba', 'Ritmos latinos', 'Coreografía'],
      gallery: [],
    },
    {
      id: 8,
      name: 'Patricia Vera',
      avatar: 'https://i.pravatar.cc/128?img=32',
      category: 'limpieza',
      categoryLabel: 'Limpieza',
      rating: 4.9,
      reviews: 165,
      distance: 1.0,
      priceMin: 25000,
      priceMax: 70000,
      priceUnit: 'jornada',
      city: 'Viña del Mar',
      lat: -33.028,
      lng: -71.548,
      verified: true,
      available: true,
      completedJobs: 298,
      responseTime: '~5 min',
      bio: 'Servicio de limpieza doméstica y de oficinas. Limpieza general, profunda, post-construcción y de fin de arriendo. Con sus propios materiales.',
      skills: ['Limpieza general', 'Limpieza profunda', 'Post-construcción', 'Oficinas', 'Fin de arriendo'],
      gallery: [],
    },
    {
      id: 9,
      name: 'Felipe Núñez',
      avatar: 'https://i.pravatar.cc/128?img=67',
      category: 'gasfiteria',
      categoryLabel: 'Gasfitería',
      rating: 4.6,
      reviews: 89,
      distance: 5.3,
      priceMin: 18000,
      priceMax: 55000,
      priceUnit: 'visita',
      city: 'Villa Alemana',
      lat: -33.042,
      lng: -71.375,
      verified: true,
      available: true,
      completedJobs: 167,
      responseTime: '~35 min',
      bio: 'Gasfiter con amplia experiencia en sistemas de agua caliente y fría. Disponible fines de semana.',
      skills: ['Agua caliente', 'Termostatos', 'Duchas', 'Lavamanos', 'Filtraciones'],
      gallery: [],
    },
    {
      id: 10,
      name: 'Marco Espinoza',
      avatar: 'https://i.pravatar.cc/128?img=59',
      category: 'electricidad',
      categoryLabel: 'Electricidad',
      rating: 4.7,
      reviews: 103,
      distance: 6.1,
      priceMin: 20000,
      priceMax: 90000,
      priceUnit: 'proyecto',
      city: 'Quilpué',
      lat: -33.055,
      lng: -71.450,
      verified: false,
      available: true,
      completedJobs: 134,
      responseTime: '~40 min',
      bio: 'Electricista residencial con certificación en proceso. Trabajos de calidad garantizada.',
      skills: ['Enchufes', 'Interruptores', 'Iluminación', 'Revisiones', 'Alarmas'],
      gallery: [],
    },
  ],

  clients: [
    {
      id: 101,
      name: 'Sofía Mendoza',
      avatar: 'https://i.pravatar.cc/128?img=2',
      city: 'Viña del Mar',
      memberSince: '2025-01',
      totalServices: 14,
      lat: -33.022,
      lng: -71.548,
    },
    {
      id: 102,
      name: 'Andrés Morales',
      avatar: 'https://i.pravatar.cc/128?img=51',
      city: 'Valparaíso',
      memberSince: '2025-03',
      totalServices: 7,
      lat: -33.040,
      lng: -71.612,
    },
    {
      id: 103,
      name: 'Isabella Torres',
      avatar: 'https://i.pravatar.cc/128?img=16',
      city: 'Viña del Mar',
      memberSince: '2025-02',
      totalServices: 22,
      lat: -33.028,
      lng: -71.560,
    },
  ],

  bookings: [
    {
      id: 'VOY-001',
      clientId: 101,
      workerId: 1,
      category: 'gasfiteria',
      service: 'Reparación de filtración',
      status: 'completed',
      date: '2026-03-08',
      time: '10:00',
      address: 'Av. 15 Norte 845, Viña del Mar',
      price: 35000,
      commission: 5250,
      rating: 5,
      review: 'Excelente trabajo, muy puntual y prolijo.',
    },
    {
      id: 'VOY-002',
      clientId: 103,
      workerId: 3,
      category: 'belleza',
      service: 'Corte y colorimetría',
      status: 'active',
      date: '2026-03-12',
      time: '15:00',
      address: 'Calle Valparaíso 320, Viña del Mar',
      price: 42000,
      commission: 6300,
      rating: null,
      review: null,
    },
    {
      id: 'VOY-003',
      clientId: 102,
      workerId: 2,
      category: 'electricidad',
      service: 'Instalación punto de luz',
      status: 'pending',
      date: '2026-03-15',
      time: '09:00',
      address: 'Blanco 1254, Valparaíso',
      price: 45000,
      commission: 6750,
      rating: null,
      review: null,
    },
  ],

  stats: {
    totalWorkers: 548,
    totalClients: 3241,
    totalServices: 12890,
    avgRating: 4.8,
    totalRevenue: 89450000,
    pendingVerifications: 12,
  },
};

/* Helpers */
const VOY = {
  formatCLP(amount) {
    return new Intl.NumberFormat('es-CL', { style: 'currency', currency: 'CLP', minimumFractionDigits: 0 }).format(amount);
  },
  formatDistance(km) {
    return km < 1 ? `${(km * 1000).toFixed(0)} m` : `${km.toFixed(1)} km`;
  },
  getCategoryById(id) {
    return VOY_DATA.categories.find(c => c.id === id);
  },
  getWorkersByCategory(cat) {
    if (!cat || cat === 'all') return VOY_DATA.workers;
    return VOY_DATA.workers.filter(w => w.category === cat);
  },
  filterByDistance(workers, maxKm) {
    return workers.filter(w => w.distance <= maxKm);
  },
  renderStars(rating) {
    const full  = Math.floor(rating);
    const half  = rating % 1 >= 0.5 ? 1 : 0;
    const empty = 5 - full - half;
    return '★'.repeat(full) + (half ? '½' : '') + '☆'.repeat(empty);
  },
  showToast(message, type = 'info') {
    const container = document.getElementById('toast-container');
    if (!container) return;
    const icons = { info: '💡', success: '✅', error: '❌', warning: '⚠️' };
    const toast = document.createElement('div');
    toast.className = `toast ${type}`;
    toast.innerHTML = `<span>${icons[type]}</span><span>${message}</span>`;
    container.appendChild(toast);
    setTimeout(() => {
      toast.style.animation = 'fadeOut 0.3s ease forwards';
      setTimeout(() => toast.remove(), 300);
    }, 3500);
  },
  openModal(id) {
    document.getElementById(id)?.classList.add('active');
    document.body.style.overflow = 'hidden';
  },
  closeModal(id) {
    document.getElementById(id)?.classList.remove('active');
    document.body.style.overflow = '';
  },
};
